spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/todo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace